Fix following error in psutil.Process.cpu_percent method:
2016-04-01 13:44:39,299 [12628] nginx_metrics failed to collect metrics workers_cpu due to AttributeError
2016-04-01 13:44:39,299 [12628] nginx_metrics additional info:
Traceback (most recent call last):
  File "/usr/local/src/nginx-amplify/nginx-amplify-agent/amplify/agent/containers/nginx/collectors/metrics.py", line 49, in collect
    method()
  File "/usr/local/src/nginx-amplify/nginx-amplify-agent/amplify/agent/containers/nginx/collectors/metrics.py", line 182, in workers_cpu
    u, s = p.cpu_percent()
  File "/usr/local/src/nginx-amplify/nginx-amplify-agent/amplify/agent/util/ps.py", line 38, in cpu_percent
    if psutil._POSIX:
AttributeError: 'module' object has no attribute '_POSIX'